include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_final_locals
    - prefer_const_constructors
    - avoid_print

analyzer:
  plugins:
    - custom_lint

formatter:
  trailing_commas: preserve
